### ISSUE TITLE
Command was killed with SIGABRT

### ISSUE THREAD

**Issue by zixuan96** [wangonya/flexible-gatsby#1] opened 2019-12-12 18:36 UTC
When I'm going to create a Gatsby site, the terminal says _Command was killed with SIGABRT (Aborted): npm install_.

**Comment by wangonya** [comment] 2019-12-14 05:53
Hey @Hsuanr , could you share some more information about this?
What OS are you on? Gatsby version? The steps you followed to create the site? etc

**Comment by Hsuanr** [comment] 2019-12-14 06:31
Hi @wangonya ,  I'm running it on macOS 10.15.2 (19C57). and Gatsby CLI version is 2.8.18.

System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    npm: 6.13.2 - /usr/local/bin/npm
Languages:
    Python: 2.7.16 - /usr/bin/python
Browsers:
    Chrome: 78.0.3904.108
    Safari: 13.0.4
npmGlobalPackages:
    gatsby-cli: 2.8.18

I followed your _Quick Start Tutorial_, but it failed.

**Comment by wangonya** [comment] 2019-12-14 13:21
@Hsuanr sorry but I'm not able to reproduce your error. I've followed the quickstart to create a new site and it works fine. I've tested it on a Mac, but I'll also check it out on my Linux machine to see if I get something different.

I'll leave this open in case anyone else faces the same issue or has more info on it. Feel free to close it or provide more info when you figure something out.

**Comment by wangonya** [comment] 2020-07-23 14:25
Closing this due to inactivity. Feel free to reopen if you're still facing the issue.

**Closed by wangonya** 2020-07-23 14:25 UTC
